version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-resume-review-postgres-dev
    environment:
      POSTGRES_DB: ai_resume_review_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - ai-resume-review-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_resume_review_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: ai-resume-review-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-resume-review-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: ai-resume-review-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@airesumereview.com
      PGADMIN_DEFAULT_PASSWORD: dev_pgadmin_123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ai-resume-review-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: ai-resume-review-postgres-data
  redis_data:
    name: ai-resume-review-redis-data
  pgadmin_data:
    name: ai-resume-review-pgadmin-data

networks:
  ai-resume-review-network:
    name: ai-resume-review-network
    driver: bridge