# Industry configurations for resume analysis
# Can be edited by recruiters/product managers

industries:
  tech_consulting:
    display_name: "Technology Consulting"
    key_skills:
      - Python
      - JavaScript
      - Cloud Architecture
      - System Design
      - Agile
      - DevOps

  finance_banking:
    display_name: "Finance & Banking"
    key_skills:
      - Financial Modeling
      - Risk Management
      - Regulatory Compliance
      - Bloomberg
      - Excel
      - VBA

  general_business:
    display_name: "General Business"
    key_skills:
      - Project Management
      - Strategic Planning
      - Data Analysis
      - Leadership
      - Communication
      - Problem Solving

  system_integrator:
    display_name: "Systems Integration"
    key_skills:
      - Systems Integration
      - Enterprise Architecture
      - API Development
      - Database Management
      - Testing
      - Implementation

  strategy_consulting:
    display_name: "Strategy Consulting"
    key_skills:
      - Strategic Analysis
      - Market Research
      - Business Modeling
      - PowerPoint
      - Excel
      - Client Management

  full_service_consulting:
    display_name: "Full Service Consulting"
    key_skills:
      - Business Analysis
      - Change Management
      - Process Improvement
      - Stakeholder Management
      - Presentation
      - Analytics
