# ============================================================================
# Cloud Run Service Configuration: Frontend Production
# ============================================================================
#
# PURPOSE:
#   Define Cloud Run service configuration for the frontend production environment.
#
# DESIGN DECISIONS (Production-specific):
#   Memory: 512MB
#     - Same as staging
#
#   CPU: 1 vCPU
#     - Same as staging
#
#   Min Instances: 0
#     - Reason: Frontend scales to zero when no traffic
#     - Cost optimization (frontend is cheaper to scale)
#     - Cold start acceptable for frontend (2-3 seconds)
#
#   Max Instances: 10 ⭐ DIFFERENT FROM STAGING
#     - Reason: Handle more concurrent users
#     - Each instance serves ~80 concurrent users
#     - Total capacity: ~800 concurrent users
#
#   Concurrency: 80
#     - Same as staging
#
#   Timeout: 300 seconds
#     - Same as staging
#
# PRODUCTION-SPECIFIC FEATURES:
#   - Custom domain mapping (future):
#     - app.yourcompany.com → Frontend
#   - CDN (future):
#     - Cloud CDN for static assets
#   - Performance monitoring:
#     - Core Web Vitals tracking
#     - Page load time metrics
#
# ENVIRONMENT VARIABLES:
#   NEXT_PUBLIC_API_URL:
#     - Points to backend production service
#     - Will change to custom domain (api.yourcompany.com)
#
# NEXT STEPS FOR IMPLEMENTATION:
#   1. Configure custom domain
#   2. Enable Cloud CDN (optional)
#   3. Set up performance monitoring
#   4. Test scalability under load
#
# ============================================================================

# TODO: Implement Cloud Run service configuration in YAML format
