# ============================================================================
# Cloud Run Service Configuration: Backend Staging
# ============================================================================
#
# PURPOSE:
#   Define Cloud Run service configuration for the backend staging environment.
#   This file is used by `gcloud run services replace` command.
#
# USAGE:
#   gcloud run services replace deployment/configs/cloud-run-backend-staging.yaml
#
# WHAT THIS FILE DEFINES:
#   - Service name
#   - Container image location
#   - Resource limits (CPU, memory)
#   - Scaling configuration (min/max instances)
#   - Environment variables
#   - IAM permissions
#   - Network settings (VPC, Cloud SQL connection)
#
# DESIGN DECISIONS:
#   Memory: 2GB
#     - Reason: LangChain/LangGraph AI agents need memory
#     - Can be increased if out-of-memory errors occur
#
#   CPU: 2 vCPU
#     - Reason: AI processing is CPU-intensive
#     - Handles 20 concurrent requests efficiently
#
#   Min Instances: 0
#     - Reason: Cost optimization for staging
#     - Cold start acceptable in staging environment
#
#   Max Instances: 10
#     - Reason: Prevent runaway costs in staging
#     - Sufficient for testing load
#
#   Concurrency: 20
#     - Reason: AI processing is resource-intensive
#     - Each request may take 30-60 seconds
#     - Lower concurrency = better performance
#
#   Timeout: 600 seconds (10 minutes)
#     - Reason: AI analysis can take up to 5 minutes
#     - Includes time for OpenAI API calls
#
# ENVIRONMENT VARIABLES:
#   Non-sensitive values are listed here directly.
#   Sensitive values (API keys, passwords) are fetched from Secret Manager.
#
# CLOUD SQL CONNECTION:
#   - Uses Unix socket (not TCP)
#   - Private IP only (no public access)
#   - Connection string: /cloudsql/PROJECT:REGION:INSTANCE
#
# IAM PERMISSIONS:
#   Service account needs:
#   - roles/cloudsql.client (Cloud SQL connection)
#   - roles/secretmanager.secretAccessor (Secret Manager access)
#
# NEXT STEPS FOR IMPLEMENTATION:
#   1. Replace placeholders with actual values
#   2. Create service account
#   3. Grant IAM permissions
#   4. Deploy using gcloud command
#
# ============================================================================

# TODO: Implement Cloud Run service configuration in YAML format
# Reference: https://cloud.google.com/run/docs/reference/yaml/v1
